### PR TITLE
Add support for retrieving a single pool's addresses in asset find

### PR DESCRIPTION
**Pull request by ssgelm**
Currently, the only way to retrieve the addresses for an asset is to get all addresses associated with an asset.  It's pretty common for us to have multiple addresses per asset (e.g. management network, application network) so it's a minor hassle for us to have to parse it.  This allows
for a special tag of `addresses_POOLNAME`, where `POOLNAME` (obviously) is an ip address pool.  Any addresses in that pool are then passed into `format_asset_value` and thereby formatted like the `addresses` tag.

### CODE REVIEW

**Comment by defect** [comment]
I apologize the delay and for `collins_shell` being kind of neglected. To be honest, we don't actually use it much (actually at all) at tumblr these days.

That being said, this looks great to me. It's not changing the behavior of previous versions, just adding a feature. If you want, feel free to [bump the version](https://github.com/tumblr/collins_shell/blob/master/VERSION) and add your self to the [authors](https://github.com/tumblr/collins_shell/blob/master/collins_shell.gemspec#L6). If not, i'll do the version bump before publishing to rubygems.

cc @byxorna @qx-xp @gtorre @Mitsuwa

**Comment by ssgelm** [comment]
@defect I did both of those things.  Thanks!

**Comment by ssgelm** [comment]
@defect Out of curiosity are you not using collins at all anymore or are you using a different client for it?

**Comment by defect** [comment]
We are definitely using collins! It drives all our automation so for us it's here to stay for the foreseeable future :) Most of the infra engineers over here are using @byxorna 's [collins-cli](https://github.com/byxorna/collins-cli) for CLI queries/ad-hoc things these days, and good ol' [`collins_client`](https://github.com/tumblr/collins_client) for programmatic things.

Edit: Oh, and [collins_auth](https://github.com/tumblr/collins_auth) just makes it super simple to use `collins_client`.

**Comment by ssgelm** [comment]
Ah yeah I've intended to switch over to that but change is hard :).  We also have a ton of scripts using collins_client of course.  I'll give collins-cli a closer look soon.  Regardless, this tweak here will definitely help us in the meantime!  Thanks so much for giving it a once-over.

**Comment by defect** [comment]
The best thing about collins-cli is that you can pipe it to itself and other tools, and do cool things. Like, "provision 10 web nodes from boxes in Unallocated state".
```
collins find -S Unallocated | shuf | head -10 | collins prov -n webnode --build-contact felix
```
and you're done! 

Anyway, i'll merge and publish your change now. 0.2.26 should be on rubygems shortly

**Pull request merged**
