### PR TITLE
Add support for deleting a single IP address from an asset

### PR DESCRIPTION
**Pull request by ssgelm**
This is work that was originally in tumblr/collins#505.  It depends on tumblr/collins_client#6 being merged (and assumes that version will be released as 0.3.2).  I opted for a separate command instead of overloading `delete` because it seemed more straightforward for the user.

### CODE REVIEW

**Review by komapa — APPROVED** [review]
🚅 LGTM

**Comment by ssgelm** [comment]
Is this ok to be merged?

**Comment by komapa** [comment]
Hey @ssgelm, we are currently in some legal limbo with the new owner of Tumblr. We are trying to figure out the CLA situation before we can merge any PRs from contributors. Sorry about that!

**Comment by ssgelm** [comment]
Ah no worries, I understand!

**Comment by ssgelm** [comment]
@komapa Any update on this?

**Comment by ssgelm** [comment]
@kirooshu Any updates here? If you're not able to merge this I totally understand but it would be helpful to know, as I may have to just end up forking it to make installation a little easier for us. (To be clear this very much isn't a threat! I'd much rather just see the change merged 😄 )

**Pull request merged**
